#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! slskd
//! Source: slskd-oapi.json
//! Version: v0
//! Generated by `oas3-gen v0.26.2`
//!
//! A modern client-server application for the Soulseek file sharing network

use serde::{Deserialize, Serialize};
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(deny_unknown_fields)]
pub(crate) struct LoginRequest {
    pub(crate) username: Option<String>,
    pub(crate) password: Option<String>,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, oas3_gen_support::Default)]
#[serde(deny_unknown_fields)]
pub(crate) struct TokenResponse {
    /// Gets the time at which the Access Token expires.
    pub(crate) expires: Option<i64>,
    /// Gets the time at which the Access Token was issued.
    pub(crate) issued: Option<i64>,
    /// Gets the value of the Name claim from the Access Token.
    pub(crate) name: Option<String>,
    /// Gets the value of the Not Before claim from the Access Token.
    #[serde(rename = "notBefore")]
    pub(crate) not_before: Option<i64>,
    /// Gets the Access Token string.
    pub(crate) token: Option<String>,
    /// Gets the Token type.
    #[serde(rename = "tokenType")]
    pub(crate) token_type: Option<String>,
}
/// A search request.
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(deny_unknown_fields)]
pub(crate) struct SearchRequest {
    /// Gets or sets the unique search identifier.
    pub(crate) id: Option<uuid::Uuid>,
    /// Gets or sets the maximum number of file results to accept before the search is considered complete. (Default = 10,000).
    #[serde(rename = "fileLimit")]
    #[validate(range(min = 0i32, max = i32::MAX))]
    pub(crate) file_limit: Option<i32>,
    /// Gets or sets a value indicating whether responses are to be filtered. (Default = true).
    #[serde(rename = "filterResponses")]
    pub(crate) filter_responses: Option<bool>,
    /// Gets or sets the maximum queue depth a peer may have in order for a response to be processed. (Default = 1000000).
    #[serde(rename = "maximumPeerQueueLength")]
    #[validate(range(min = 0i32, max = i32::MAX))]
    pub(crate) maximum_peer_queue_length: Option<i32>,
    /// Gets or sets the minimum upload speed a peer must have in order for a response to be processed. (Default = 0).
    #[serde(rename = "minimumPeerUploadSpeed")]
    #[validate(range(min = 0i32, max = i32::MAX))]
    pub(crate) minimum_peer_upload_speed: Option<i32>,
    /// Gets or sets the minimum number of files a response must contain in order to be processed. (Default = 1).
    #[serde(rename = "minimumResponseFileCount")]
    #[validate(range(min = 0i32, max = i32::MAX))]
    pub(crate) minimum_response_file_count: Option<i32>,
    /// Gets or sets the maximum number of search results to accept before the search is considered complete. (Default = 100).
    #[serde(rename = "responseLimit")]
    #[validate(range(min = 0i32, max = i32::MAX))]
    pub(crate) response_limit: Option<i32>,
    /// Gets or sets the search text.
    #[serde(rename = "searchText")]
    pub(crate) search_text: Option<String>,
    /// Gets or sets the search timeout value, in seconds, used to determine when the search is complete. (Default = 15).
    #[serde(rename = "searchTimeout")]
    #[validate(range(min = 5i32, max = i32::MAX))]
    pub(crate) search_timeout: Option<i32>,
}
#[serde_with::skip_serializing_none]
#[derive(
    Debug, Clone, PartialEq, Serialize, Deserialize, validator::Validate, oas3_gen_support::Default,
)]
#[serde(deny_unknown_fields)]
pub(crate) struct QueueDownloadRequest {
    /// Gets or sets the filename to download.
    #[validate(length(min = 1u64))]
    pub(crate) filename: String,
    /// Gets or sets the size of the file.
    pub(crate) size: Option<i64>,
}
