---
services:
  yoink:
    build: .
    container_name: yoink
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - yoink-data:/data
      - ./music:/music
      - ./development/slskd-data:/app
    environment:
      RUST_BACKTRACE: 1
      AUTH_DISABLED: true
      DOWNLOAD_LYRICS: true
      DATABASE_URL: postgres://yoink:yoink@postgres:5432/yoink
  postgres:
    image: postgres:18-alpine
    container_name: yoink-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yoink
      POSTGRES_PASSWORD: yoink
      POSTGRES_DB: yoink
    volumes:
      - postgres-data:/var/lib/postgresql
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SWAGGER=true
    volumes:
      - ./development/slskd-data:/app
      - ./music:/music
    env_file:
      - .env.docker
    restart: always

  hifi-api:
    image: ghcr.io/binimum/hifi-api:main
    container_name: hifi-api
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - .env.hifi
    ports:
      - 3005:8000

volumes:
  yoink-data:
  postgres-data:
