[tools]
"cargo:cargo-leptos" = "latest"
"cargo:sqlx-cli" = { version = "latest", features = "sqlite" }
"github:tursodatabase/turso" = "latest"

[tasks.lint-server]
run = "cargo clippy --package yoink-server -- -D warnings"

[tasks.run-server]
run = "cargo run -p yoink-server"
sources = ["crates/**", "**/.env*"]

[tasks.dev-server]
run = "mise watch -r run-server"

[tasks.lint]
depends = ["lint-server"]

[tasks.dev]
run = "cargo leptos watch"
alias = "d"
