[tools]
"cargo:cargo-leptos" = "latest"
"cargo:cargo-tarpaulin" = "latest"
"cargo:sqlx-cli" = { version = "latest", features = "sqlite" }
"github:tursodatabase/turso" = "latest"

[tasks.lint-server]
run = "cargo clippy --package yoink-server -- -D warnings"

[tasks.run-server]
run = "cargo run -p yoink-server"

[tasks.dev-server]
run = "mise watch -r -w crates -W Cargo.toml -W .env run-server"

[tasks.gen-frontend-types]
alias = "gt"
dir = "frontend"
run = "bun x openapi-typescript http://localhost:3000/docs/openapi.json --output src/lib/api/types.gen.ts"

[tasks.lint]
depends = ["lint-server"]

[tasks.dev]
depends = ["dev-server"]
alias = "d"
