#![allow(clippy::default_trait_access)]
#![allow(clippy::doc_markdown)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::missing_panics_doc)]
#![allow(clippy::result_large_err)]
#![allow(clippy::struct_field_names)]
#![allow(clippy::too_many_lines)]
#![allow(clippy::unnecessary_wraps)]
#![allow(clippy::unused_self)]
#![allow(dead_code)]
//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! HiFi-RestAPI
//! Source: hifi-oapi.json
//! Version: 2.10
//! Generated by `oas3-gen v0.26.2`
//!
//! Tidal Music Proxy

use serde::{Deserialize, Serialize};
use validator::Validate;
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub(crate) struct HTTPValidationError {
    pub(crate) detail: Option<Vec<ValidationError>>,
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
pub(crate) struct ValidationError {
    pub(crate) loc: Vec<LocKind>,
    pub(crate) msg: String,
    #[serde(rename = "type")]
    pub(crate) r#type: String,
    pub(crate) input: Option<serde_json::Value>,
    pub(crate) ctx: Option<serde_json::Value>,
}
/// Index
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct IndexGetRequest {}
impl IndexGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(req: reqwest::Response) -> anyhow::Result<IndexGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(IndexGetResponse::Ok);
        }
        let _ = req.bytes().await?;
        return Ok(IndexGetResponse::Unknown);
    }
}
/// Response types for index__get
#[derive(Debug, Clone)]
pub(crate) enum IndexGetResponse {
    ///200: Successful Response
    Ok,
    ///default: Unknown response
    Unknown,
}
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetInfoInfoGetRequestQuery {
    pub(crate) id: i64,
}
/// Get Info
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetInfoInfoGetRequest {
    pub(crate) query: GetInfoInfoGetRequestQuery,
}
impl GetInfoInfoGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetTrackTrackGetRequestQuery {
    pub(crate) id: i64,
    #[default(Some("HI_RES_LOSSLESS".to_string()))]
    pub(crate) quality: Option<String>,
    #[default(Some(false))]
    pub(crate) immersiveaudio: Option<bool>,
}
/// Get Track
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetTrackTrackGetRequest {
    pub(crate) query: GetTrackTrackGetRequestQuery,
}
impl GetTrackTrackGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetTrackManifestsTrackManifestsGetRequestQuery {
    #[validate(length(min = 1u64))]
    pub(crate) id: String,
    #[default(Some(Default::default()))]
    pub(crate) formats: Option<Vec<String>>,
    #[default(Some("true".to_string()))]
    pub(crate) adaptive: Option<String>,
    #[serde(rename = "manifestType")]
    #[default(Some("MPEG_DASH".to_string()))]
    pub(crate) manifest_type: Option<String>,
    #[serde(rename = "uriScheme")]
    #[default(Some("HTTPS".to_string()))]
    pub(crate) uri_scheme: Option<String>,
    #[default(Some("PLAYBACK".to_string()))]
    pub(crate) usage: Option<String>,
}
/// Get Track Manifests
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetTrackManifestsTrackManifestsGetRequest {
    #[validate(nested)]
    pub(crate) query: GetTrackManifestsTrackManifestsGetRequestQuery,
}
impl GetTrackManifestsTrackManifestsGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
/// Widevine Proxy
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct WidevineProxyWidevinePostRequest {}
impl WidevineProxyWidevinePostRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(req: reqwest::Response) -> anyhow::Result<IndexGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(IndexGetResponse::Ok);
        }
        let _ = req.bytes().await?;
        return Ok(IndexGetResponse::Unknown);
    }
}
/// Widevine Proxy
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct WidevineProxyWidevinePost2Request {}
impl WidevineProxyWidevinePost2Request {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(req: reqwest::Response) -> anyhow::Result<IndexGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(IndexGetResponse::Ok);
        }
        let _ = req.bytes().await?;
        return Ok(IndexGetResponse::Unknown);
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetRecommendationsRecommendationsGetRequestQuery {
    pub(crate) id: i64,
}
/// Get Recommendations
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetRecommendationsRecommendationsGetRequest {
    pub(crate) query: GetRecommendationsRecommendationsGetRequestQuery,
}
impl GetRecommendationsRecommendationsGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct SearchSearchGetRequestQuery {
    pub(crate) s: Option<String>,
    pub(crate) a: Option<String>,
    pub(crate) al: Option<String>,
    pub(crate) v: Option<String>,
    pub(crate) p: Option<String>,
    /// ISRC query
    pub(crate) i: Option<String>,
    #[validate(range(min = 0i64))]
    #[default(Some(0i64))]
    pub(crate) offset: Option<i64>,
    #[validate(range(min = 1i64, max = 500i64))]
    #[default(Some(25i64))]
    pub(crate) limit: Option<i64>,
}
/// Search endpoint supporting track/artist/album/video/playlist queries via distinct params.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct SearchSearchGetRequest {
    #[validate(nested)]
    pub(crate) query: SearchSearchGetRequestQuery,
}
impl SearchSearchGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetAlbumAlbumGetRequestQuery {
    /// Album ID
    pub(crate) id: i64,
    #[validate(range(min = 1i64, max = 500i64))]
    #[default(Some(100i64))]
    pub(crate) limit: Option<i64>,
    #[validate(range(min = 0i64))]
    #[default(Some(0i64))]
    pub(crate) offset: Option<i64>,
}
/// Get Album
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetAlbumAlbumGetRequest {
    #[validate(nested)]
    pub(crate) query: GetAlbumAlbumGetRequestQuery,
}
impl GetAlbumAlbumGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetMixMixGetRequestQuery {
    /// Mix ID
    #[validate(length(min = 1u64))]
    pub(crate) id: String,
}
/// Fetch items from a Tidal mix by its ID.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetMixMixGetRequest {
    #[validate(nested)]
    pub(crate) query: GetMixMixGetRequestQuery,
}
impl GetMixMixGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
/// Response types for get_mix_mix__get
#[derive(Debug, Clone)]
pub(crate) enum GetMixMixGetResponse {
    ///200: Successful Response
    Ok,
    ///422: Validation Error
    UnprocessableEntity(HTTPValidationError),
    ///default: Unknown response
    Unknown,
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetPlaylistPlaylistGetRequestQuery {
    #[validate(length(min = 1u64))]
    pub(crate) id: String,
    #[validate(range(min = 1i64, max = 500i64))]
    #[default(Some(100i64))]
    pub(crate) limit: Option<i64>,
    #[validate(range(min = 0i64))]
    #[default(Some(0i64))]
    pub(crate) offset: Option<i64>,
}
/// Fetch playlist metadata plus items concurrently, using shared client and single token.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetPlaylistPlaylistGetRequest {
    #[validate(nested)]
    pub(crate) query: GetPlaylistPlaylistGetRequestQuery,
}
impl GetPlaylistPlaylistGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetSimilarArtistsArtistSimilarGetRequestQuery {
    /// Artist ID
    pub(crate) id: i64,
    pub(crate) cursor: Option<String>,
}
/// Fetch artists similar to another by its ID using V2 API.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetSimilarArtistsArtistSimilarGetRequest {
    pub(crate) query: GetSimilarArtistsArtistSimilarGetRequestQuery,
}
impl GetSimilarArtistsArtistSimilarGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetSimilarAlbumsAlbumSimilarGetRequestQuery {
    /// Album ID
    pub(crate) id: i64,
    pub(crate) cursor: Option<String>,
}
/// Fetch albums similar to another by its ID using V2 API.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetSimilarAlbumsAlbumSimilarGetRequest {
    pub(crate) query: GetSimilarAlbumsAlbumSimilarGetRequestQuery,
}
impl GetSimilarAlbumsAlbumSimilarGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetArtistArtistGetRequestQuery {
    pub(crate) id: Option<i64>,
    pub(crate) f: Option<i64>,
    #[default(Some(false))]
    pub(crate) skip_tracks: Option<bool>,
}
/// Artist detail or album+track aggregation.
///
/// - id: basic artist metadata + cover URLs
/// - f: fetch artist albums page and aggregate tracks across albums (capped concurrency)
/// - skip_tracks: if true, returns only albums without aggregating tracks (when using 'f')
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetArtistArtistGetRequest {
    pub(crate) query: GetArtistArtistGetRequestQuery,
}
impl GetArtistArtistGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetCoverCoverGetRequestQuery {
    pub(crate) id: Option<i64>,
    pub(crate) q: Option<String>,
}
/// Fetch album cover data for a track id or search query.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetCoverCoverGetRequest {
    pub(crate) query: GetCoverCoverGetRequestQuery,
}
impl GetCoverCoverGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetLyricsLyricsGetRequestQuery {
    pub(crate) id: i64,
}
/// Get Lyrics
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetLyricsLyricsGetRequest {
    pub(crate) query: GetLyricsLyricsGetRequestQuery,
}
impl GetLyricsLyricsGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetTopVideosTopvideosGetRequestQuery {
    #[serde(rename = "countryCode")]
    #[default(Some("US".to_string()))]
    pub(crate) country_code: Option<String>,
    #[default(Some("en_US".to_string()))]
    pub(crate) locale: Option<String>,
    #[serde(rename = "deviceType")]
    #[default(Some("BROWSER".to_string()))]
    pub(crate) device_type: Option<String>,
    #[validate(range(min = 1i64, max = 100i64))]
    #[default(Some(25i64))]
    pub(crate) limit: Option<i64>,
    #[validate(range(min = 0i64))]
    #[default(Some(0i64))]
    pub(crate) offset: Option<i64>,
}
/// Fetch recommended videos from Tidal.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetTopVideosTopvideosGetRequest {
    #[validate(nested)]
    pub(crate) query: GetTopVideosTopvideosGetRequestQuery,
}
impl GetTopVideosTopvideosGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, PartialEq, Serialize, oas3_gen_support::Default)]
pub(crate) struct GetVideoVideoGetRequestQuery {
    /// Video ID
    pub(crate) id: i64,
    /// Video quality (HIGH, MEDIUM, LOW)
    #[default(Some("HIGH".to_string()))]
    pub(crate) quality: Option<String>,
    /// Playback mode (STREAM, OFFLINE)
    #[default(Some("STREAM".to_string()))]
    pub(crate) mode: Option<String>,
    /// Asset presentation (FULL, PREVIEW)
    #[default(Some("FULL".to_string()))]
    pub(crate) presentation: Option<String>,
}
/// Fetch video playback info from Tidal.
#[derive(Debug, Clone, validator::Validate, oas3_gen_support::Default)]
pub(crate) struct GetVideoVideoGetRequest {
    pub(crate) query: GetVideoVideoGetRequestQuery,
}
impl GetVideoVideoGetRequest {
    /// Parse the HTTP response into the response enum.
    pub(crate) async fn parse_response(
        req: reqwest::Response,
    ) -> anyhow::Result<GetMixMixGetResponse> {
        let status = req.status();
        if status == http::StatusCode::OK {
            let _ = req.bytes().await?;
            return Ok(GetMixMixGetResponse::Ok);
        }
        if status == http::StatusCode::UNPROCESSABLE_ENTITY {
            let data =
                oas3_gen_support::Diagnostics::<HTTPValidationError>::json_with_diagnostics(req)
                    .await?;
            return Ok(GetMixMixGetResponse::UnprocessableEntity(data));
        }
        let _ = req.bytes().await?;
        return Ok(GetMixMixGetResponse::Unknown);
    }
}
#[derive(Debug, Clone, PartialEq, Deserialize, oas3_gen_support::Default)]
#[serde(untagged)]
pub(crate) enum LocKind {
    #[default]
    String(String),
    Integer(i64),
}
