name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bun:
    runs-on: ubuntu-latest
    name: Bun ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Test
            cmd: test
          - name: Lint
            cmd: lint
          - name: Format Check
            cmd: fmt:check
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: mise
        uses: jdx/mise-action@v3
        with:
          install_args: "bun"
      - name: Install dependencies
        run: bun ci
        working-directory: frontend
      - run: bun ${{ matrix.cmd }}
        working-directory: frontend
  bun-build:
    runs-on: ubuntu-latest
    name: Bun Build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: mise
        uses: jdx/mise-action@v3
        with:
          install_args: "bun"
      - name: Install dependencies
        run: bun ci
      - run: bun run build
        working-directory: frontend
      - name: Upload static frontend
        uses: actions/upload-artifact@v7
        with:
          name: frontend
          path: frontend/dist

  cargo:
    runs-on: ubuntu-latest
    name: Cargo ${{ matrix.name }}
    needs: bun-build
    strategy:
      matrix:
        include:
          - name: Test
            key: test
            cmd: nextest run
          - name: Lint
            key: lint
            cmd: clippy --all-targets --all-features -- -D warnings
          - name: Format Check
            key: format
            cmd: fmt --check
          - name: Check unused dependencies
            key: shear
            cmd: shear
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: ${{ matrix.key }}
      - name: mise
        uses: jdx/mise-action@v3
        with:
          install_args: "cargo-binstall cargo:cargo-nextest cargo:cargo-shear"
      - name: Download frontend
        uses: actions/download-artifact@v8
        with:
          name: frontend
          path: frontend/dist
      - run: cargo ${{ matrix.cmd }}

  docker:
    name: Docker
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build.yaml
    secrets: inherit
    with:
      push: true
